backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://altusyabekusya.netlify.app
logo_url: https://altusyabekusya.netlify.app

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - file: "content/index.md"
        label: "Главная"
        name: "home"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "body", widget: "markdown" }
